id: P004437
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:21:37.454616
source_metadata:
  id: bdr:W1KG14738
  title: བཤད་པ་ངག་གི་སྒྱུ་རྩལ།
  author: ''
  volumes:
    3a12f840ab284f1fb2d09f3cd1dedccc:
      image_group_id: I2PD18810
      title: ''
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
